default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  usename: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_URL'] %>

development:
  <<: *default
  database: store_development

 
test:
  <<: *default
  database: store_test
  url: <%= ENV['DATABASE_URL'] %>


production:
  <<: *default
  database: store_production
  username: store
  url: <%= ENV['DATABASE_URL'] %>
