:concurrency: 3
:timeout: 60
:verbose: true
:queues:
  - critical
  - default
  - mailers
  - active_storage_analysis
  - active_storage_purge

:scheduler:
  :schedule:
    mark_cart_as_abandoned:
      cron: '*/5 * * * *' # A cada 5 minutos
      class: MarkCartAsAbandonedJob
    purge_abandoned_carts:
      cron: '0 4 * * 0' # Todo domingo as 4h da manha
      class: PurgeAbandonedCartsJob
